= NBNL build environment for data products 

== Users

It is recommended to use the `.devcontainer.json` file to run a Dev Container for your modeling work.

== Developers

=== Building and publishing a new version

First, make sure all commits are synced with remote by pushing:

[source,shell]
....
$ git push
....

Go to the https://github.com/Netbeheer-Nederland/build-dp/releases[Releases] page of this repository on GitHub, determine the version specifier of the new release -- e.g. `0.11` -- and create a new release for it.

Moving on, we want to build the new Docker image and publish it.

Ensure you are logged into GHCR:

[source,shell]
....
$ docker login
....

Make sure the current working directory is the repository root. Then, to build the Docker image, run:

[source,shell]
....
$ docker build -t ghcr.io/netbeheer-nederland/build-dp:<VERSION> -t ghcr.io/netbeheer-nederland/build-dp:latest .
....

where `<VERSION>` corresponds to the version specifier determined earlier (e.g. `0.11`).

If building has succeeded, push the built image to GHCR:

[source,shell]
....
$ docker push ghcr.io/netbeheer-nederland/build-dp:latest
....
