= NBNL build environment for data products 

== Users

It is recommended to use the `.devcontainer.json` file to run a Dev Container for your modeling work.

=== SSH keys

To use your local SSH keys in the Dev Container, simply run a `ssh-agent` session and add the identities of interest to it.

'''

==== Example

Start an SSH agent session:

[source,shell]
....
$ eval $(ssh-agent -s)
Agent pid 97280
....

Add your private key:

[source,shell]
....
$ ssh-add
....

Optionally you can pass in the private keys as arguments.

'''

Please consult other resources for more information.

== Developers

=== Publishing images

First, make sure all commits are synced with remote by pushing:

[source,shell]
....
$ git push
....

Ensure you are logged into GHCR:

[source,shell]
....
$ docker login
....

==== `upcoming` version

The `upcoming` version is intended for testing the most recent changes to `build-dp` without it affecting CI/CD pipelines and users's Dev Containers.

Make sure the current working directory is the repository root. Then, to build the Docker image, run:

[source,shell]
....
$ docker build -t ghcr.io/netbeheer-nederland/build-dp:upcoming .
....

If building has succeeded, push the built image to GHCR:

[source,shell]
....
$ docker push ghcr.io/netbeheer-nederland/build-dp:upcoming
....

==== New release

Go to the https://github.com/Netbeheer-Nederland/build-dp/releases[Releases] page of this repository on GitHub, determine the version specifier of the new release -- e.g. `0.11` -- and create a new release for it.

Moving on, we want to build the new Docker image and publish it.


Make sure the current working directory is the repository root. Then, to build the Docker image, run:

[source,shell]
....
$ docker build -t ghcr.io/netbeheer-nederland/build-dp:<VERSION> -t ghcr.io/netbeheer-nederland/build-dp:latest .
....

where `<VERSION>` corresponds to the version specifier determined earlier (e.g. `0.11`).

If building has succeeded, push the built image to GHCR:

[source,shell]
....
$ docker push ghcr.io/netbeheer-nederland/build-dp:<VERSION>
...
$ docker push ghcr.io/netbeheer-nederland/build-dp:latest
...
....
