set shell := ["bash", "-uc"]

name := shell("yq .name src/model/*.linkml.yml")
fname := replace(name, "-", "_")
title := shell("yq .title ./src/model/*.linkml.yml")
site_title := shell("yq .title src/model/*.linkml.yml")
ref_name := env("REF_NAME", shell("git rev-parse --abbrev-ref HEAD")) 
version := if ref_name == "main" { "upcoming" } else { ref_name }
schema_id := "https://modellen.netbeheernederland.nl/" + name + "/" + version
exchange_format := shell("yq '.annotations.exchange_format // \"\"' src/model/*.linkml.yml")

_default:
    @just --list --unsorted --justfile {{justfile()}}

# Cleans the output directory
_clean target="":
    #!/bin/bash
    set -e
    echo "Cleaning up…"
    echo
    if [ -d output/{{target}} ]; then \
        rm -rf output/{{target}}; \
    fi
    echo "… OK."
    echo

# Build and serve website locally
[group("development")]
preview: build serve

_generate-asciidoc:
    #!/bin/bash
    set -e
    echo -e "Generating documentation (AsciiDoc)…"
    mkdir -p output/docs/adoc
    cp -r src/docs/* output/docs/adoc
    yq -i 'del(.version)' output/docs/adoc/antora.yml
    yq -i '.title = "{{title}}"' output/docs/adoc/antora.yml
    echo
    echo "Generating schema documentation…"
    echo
    mkdir -p "output/docs/adoc/modules/schema"
    python -m linkml_asciidoc_generator.main \
        -o output/docs/adoc/modules/schema \
        -t /opt/build/templates \
        --render-diagrams \
        output/model/{{replace(name, "-", "_")}}.linkml.yml
    echo "Adding schema documentation to nav…"
    yq -i '.nav += ["modules/schema/nav.adoc"]' output/docs/adoc/antora.yml
    echo 'Setting `version` key…'
    yq -i '.version = "{{version}}"' output/docs/adoc/antora.yml; \
    echo 'Setting `prerelease` key if applicable…'
    if [[ "{{ref_name}}" == "main" || "{{ref_name}}" == "draft" ]]; then \
        yq -i '.prerelease = true' output/docs/adoc/antora.yml; \
    fi
    echo

_generate-schemas:
    #!/bin/bash
    set -e
    echo -e "Generating artifacts…"

    if [ "{{exchange_format}}" == "application/json" ]; then \
        echo "Generating JSON Schema…"; \
        mkdir -p output/schemas/json_schema; \
        echo; \
        gen-json-schema \
            --not-closed \
            output/model/{{fname}}.linkml.yml \
            > output/schemas/json_schema/{{fname}}.json_schema.json; \
        echo "… OK."; \
        echo; \
        echo "Generated JSON Schema at: output/schemas/json_schema/{{fname}}.json_schema.json"; \
        echo; \
    elif [ "{{exchange_format}}" == "application/ld+json" ]; then \
        echo "Generating SHACL…"; \
        mkdir -p output/schemas/shacl; \
        echo; \
        gen-shacl \
            --non-closed \
            output/model/{{fname}}.linkml.yml \
            > output/schemas/shacl/{{fname}}.shacl.ttl; \
        echo "… OK."; \
        echo; \
        echo "Generated SHACL schema at: output/schemas/shacl/{{fname}}.shacl.ttl"; \
        echo; \
    fi

_create_xrefs:
    #!/bin/bash
    shopt -s nullglob
    index_adoc=output/docs/adoc/modules/ROOT/pages/index.adoc
    attachments_dir=output/docs/adoc/modules/schema/attachments
    shacl_resid=schemas/shacl/{{fname}}.shacl.ttl
    json_schema_resid=schemas/json_schema/{{fname}}.json_schema.json

    echo -e '\n\n== Artifacts\n\n' >> $index_adoc

    # LinkML model
    echo -e 'Model::\n[unstyled]' >> $index_adoc
    echo '* xref:schema:attachment$model/{{fname}}.linkml.yml[LinkML]' >> $index_adoc

    # Schemas
    echo -e 'Schemas::\n[unstyled]' >> $index_adoc

    if [ -f $attachments_dir/$shacl_resid ]; then \
        echo "* xref:schema:attachment\$$shacl_resid[SHACL]" >> $index_adoc; \
    elif [ -f $attachments_dir/$json_schema_resid ]; then \
        echo "* xref:schema:attachment\$$json_schema_resid[JSON Schema]" >> $index_adoc; \
    fi

    # Examples
    [ ! -d $attachments_dir/examples ] || echo -e 'Examples::\n[unstyled]' >> $index_adoc
    if [ "{{exchange_format}}" == "application/ld+json" ]; then \
        for example_filepath in $attachments_dir/examples/jsonld/*.jsonld; do \
            example_resid=${example_filepath#"$attachments_dir"/}; \
            example_title=$(jq -r '.["dcterms:title"]' $example_filepath); \
            echo "* xref:schema:attachment\$$example_resid[$example_title]" >> $index_adoc; \
        done; \
    elif [ "{{exchange_format}}" == "application/json" ]; then \
        for example_filepath in $attachments_dir/examples/json/*.json; do \
            example_resid=${example_filepath#"$attachments_dir"}; \
            example_title=$(jq -r '.title' $example_filepath); \
            echo "* xref:schema:attachment\$$example_resid[$example_title]" >> $index_adoc; \
        done; \
    fi

_assemble-docs: && _create_xrefs
    cp -r output/model output/docs/adoc/modules/schema/attachments/
    [ ! -d output/schemas ] || cp -r output/schemas output/docs/adoc/modules/schema/attachments/
    [ ! -d output/examples ] || cp -r output/examples output/docs/adoc/modules/schema/attachments/

_post-process-schema:
    mkdir -p output/model
    cp src/model/{{fname}}.linkml.yml output/model/{{fname}}.linkml.yml
    yq -i '.version = "{{version}}"' output/model/{{fname}}.linkml.yml
    yq -i '.id = "{{schema_id}}"' output/model/{{fname}}.linkml.yml
    yq -i '.annotations.environment = strenv(ENV_URL)' output/model/{{fname}}.linkml.yml
    yq -i '.generation_date = "{{shell("date -I")}}"' output/model/{{fname}}.linkml.yml

# Build processing logic called by Antora Collector.
[group("development")]
_build: _clean _post-process-schema _generate-asciidoc _generate-schemas _generate-example-data _assemble-docs _validate-example-data

# Build website locally
[group("development")]
build: 
    @echo "Generating site using Antora…"
    @if [ $CI == "true" ]; then \
        jinja -D site_url "{{schema_id}}" -D site_title "{{site_title}}" /opt/build/antora/antora-playbook.yml.jinja > /tmp/antora-playbook.yml; \
        antora --fetch /tmp/antora-playbook.yml; \
    else \
        jinja -D site_url http://localhost:8080 -D site_title "{{site_title}}" /opt/build/antora/antora-playbook.local.yml.jinja > /tmp/antora-playbook.local.yml; \
        antora --fetch /tmp/antora-playbook.local.yml; \
    fi
    @echo
    @echo -e "Generated documentation files at: output/docs/html"
    @echo

# Serve the built website locally
[group("development")]
serve:
    @echo -e "Serving website from output/docs/html…"
    @echo
    http-serve output/docs/html

# Create example data
#[group("examples")]
#create-example-data:
#    @echo TODO…

_generate-example-data:
    #!/bin/bash
    set shopt -e
    shopt -s nullglob
    echo -e "Generating example data…"
    if [ "{{exchange_format}}" == "application/ld+json" ]; then \
        for example_file in src/examples/*.yml; do \
            mkdir -p output/examples/jsonld
            example_filename=$(basename $example_file); \
            example_filepath=output/examples/jsonld/${example_filename%.*}.jsonld; \
            gen-linkml-profile \
                convert \
                $example_file \
                --out $example_filepath; \
            jq '."dcterms:conformsTo" = [{"@id": "{{schema_id}}"}]' $example_filepath | sponge $example_filepath; \
        done
    elif [ "{{exchange_format}}" == "application/json" ]; then \
        for example_file in src/examples/*.yml; do \
            mkdir -p output/examples/json
            example_filename=$(basename $example_file); \
            example_filepath=output/examples/json/${example_filename%.*}.json; \
            gen-linkml-profile \
                convert \
                $example_file \
                --out $example_filepath; \
            jq '.conforms_to = "{{schema_id}}"' $example_filepath | sponge $example_filepath; \
        done
    else \
        echo "No validation checks to run."
        exit 0
    fi
    echo "… OK."
    echo
    echo -e "Generated example data at: output/examples"
    echo

_validate-example-data:
    #!/bin/bash
    shopt -s nullglob
    echo "Validating example data…"
    echo
    if [ "{{exchange_format}}" == "application/ld+json" ]; then \
        for example_file in output/examples/jsonld/*.jsonld; do \
            pyshacl -s output/schemas/shacl/{{fname}}.shacl.ttl -df json-ld -f human $example_file; \
        done; \
    elif [ "{{exchange_format}}" == "application/json" ]; then \
        for example_file in output/examples/json/*.json; do \
            check-jsonschema --schemafile output/schemas/json_schema/{{fname}}.json_schema.json $example_file; \
        done; \
    fi
    echo

# Validate example data
[group("examples")]
validate-example-data: _clean _post-process-schema _generate-schemas _generate-example-data _validate-example-data

# Update project structure to conform to latest version of template
[group("project")]
update-project:
    copier update
